title: Look Up [↑]
description: Por Ejemplo
theme: minima
plugins:
  - jekyll-feed
repository: Flatfish4u/Flatfish4u.github.io
url: https://Flatfish4u.github.io
baseurl: ""

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/